CFLAGS = \
	-Wall \
	-Wcast-align \
	-Wcast-qual \
	-Wconversion \
	-Wextra \
	-Wfatal-errors \
	-Wfloat-equal \
	-Wpointer-arith \
	-Wstrict-prototypes \
	-Wswitch-default \
	-Wswitch-enum \
	-Wundef \
	-Wunreachable-code \
	-Wwrite-strings \
	-std=$(LANG_STD) \
	-I$(INCLUDE_DIR) \
	-fno-omit-frame-pointer \
	-fno-math-errno \
	-ffinite-math-only
